services:
  app:
    build: .
    volumes:
      - .:/app
    command: /bin/bash -c "chmod +x ./setup.sh && ./setup.sh && jupyter-lab --allow-root --no-browser --ip=0.0.0.0 --port=8888 --NotebookApp.token='' --notebook-dir=/app --NotebookApp.disable_check_xsrf=True"
    ports:
      - 8888:8888
    tty: true